apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql/mysql-server
    resources:
      limits:
        cpu: "500m"
    ports:
      - containerPort: 3306
    envFrom:
      - configMapRef:
          name: istory-db-config
      - secretRef:
          name: istory-db-secret
