apiVersion: apps/v1
kind: Deployment
metadata:
  name:  istory
  labels:
    app:  istory
spec:
  selector:
    matchLabels:
      app: istory
  replicas: 3
  template:
    metadata:
      labels:
        app:  istory
    spec:
      containers:
        - name:  istory
          image:  dangtong/istory
          envFrom:
            - configMapRef:
                name: istory-app-config
          env:
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: istory-db-secret
                  key: MYSQL_PASSWORD
            - name: spring.datasource.username
              valueFrom:
                configMapKeyRef:
                  name: istory-db-config
                  key: MYSQL_USER
          resources:
            requests:
              cpu: 300m
              memory: 500Mi
            limits:
              cpu: 400m
              memory: 600Mi
          readinessProbe:
            httpGet:
              path: /actuator
              port: 8080
            initialDelaySeconds: 1
            timeoutSeconds: 3
            successThreshold: 2
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 8080
              name:  istory
